const data=[
    {id:1,
    quote:"Your heart is the size of an ocean. Go find yourself in its hidden depths.",
    author:"Rumi",
},
{id:2,
    quote:"Your heart is the size of an ocean. Go find yourself in its hidden depths.",
    author:"Rumi",
},
{id:3,
    quote:"Your heart is the size of an ocean. Go find yourself in its hidden depths.",
    author:"Rumi",
},
{id:4,
    quote:"Your heart is the size of an ocean. Go find yourself in its hidden depths.",
    author:"Rumi",
},
{id:5,
    quote:"Your heart is the size of an ocean. Go find yourself in its hidden depths.",
    author:"Rumi",
},

{id:6,
    quote:"Your heart is the size of an ocean. Go find yourself in its hidden depths.",
    author:"Rumi",
},
{id:7,
    quote:"Your heart is the size of an ocean. Go find yourself in its hidden depths.",
    author:"Rumi",
},

{id:8,
    quote:"Your heart is the size of an ocean. Go find yourself in its hidden depths.",
    author:"Rumi",
},
]
module.exports =data;